spring:
    application:
        name: example-xential-plugin
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
        time-zone: UTC
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:54340/example-core-db
        username: example
        password: password
        hikari:
            auto-commit: false

    liquibase:
        enabled: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show_sql: false
        open-in-view: false
        properties:
            hibernate:
                hbm2ddl.auto: none
                generate_statistics: false
                naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
                cache:
                    use_second_level_cache: false
                    use_query_cache: false
                    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                format_sql: true
                jdbc:
                    time_zone: UTC
                connection:
                    provider_disables_autocommit: true
        hibernate:
            ddl-auto: none
    main:
        allow-bean-definition-overriding: true

logging:
    level:
        org.springframework.beans: DEBUG
        reactor.netty.http.client.HttpClient: DEBUG

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

valtimo:
    database: postgres
    app:
        scheme: http
    oauth:
        tokenValidityInSeconds: 3600 # Token is valid 1 hour
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAooyECQIi6v4TLKOYWwXClDhJcrGcGfKZj7LQIgY/Ajm2nAKv5kiZRoS8GzMzIGKkkilAJyWQCoKlP//azHqzIxO6WZWCqGFxd04vK5JYujsiMMTNvTggfFSM7VxbzU/wv+aAEvBaGUMYp2Oamn5szzYzkzsowujvDZp+CE8ryZWTVmA+8WZE4aoU6VzfXmMDmPxvRXvktPRsJkA7hkv65TTJwUZF38goRg62kRD0hOP1sIy6vwKDSkjafLV1bYNBRiWXNReJNBXauhy74GeiHODGrI62NwUJXSgZ62cViPt6cx/3A7VBPLpEPnpnlZcIDfsFpSUuNEXc7HoLRuldbQIDAQAB

    hardening:
        removeStacktracesFromReturnedExceptions: true
        allowStacktraceOnIps:
            - 127.0.0.1
    security:
        whitelist:
            hosts:
                - localhost
    plugin:
        encryption-secret: "abcdefghijklmnop"
    changelog:
        pbac:
            clear-tables: true
        case-tabs:
            clear-tables: true
    web:
        cors:
            corsConfiguration:
                allowedOrigins:
                    - "*"
                allowedMethods:
                    - "*"
                allowedHeaders:
                    - "*"
            paths:
                - "/**"

    genericTemplateName: "template-name"

spring-actuator:
    username: admin
    password: password

audit:
    record:
        retention: 365 # days

camunda:
    bpm:
        history-level: AUDIT
        history-level-default: AUDIT
        admin-user:
            id: Admin
            password: admin
            first-name: Admin account
        generic-properties:
            properties:
                enforceHistoryTimeToLive: false


# ==================
# keycloak server to server config
# ==================
keycloak:
    realm: valtimo
    auth-server-url: http://localhost:8081/auth
    resource: valtimo-user-m2m-client
    credentials:
        secret: 6ef6ca16-6b86-482a-a3d9-0561704c1db9
